#!/bin/bash
# info: backup all users
# options: NONE
#
# The function backups all system users.


#----------------------------------------------------------#
#                    Variable&Function                     #
#----------------------------------------------------------#

# Importing system enviroment  as we run this script
# mostly by cron wich not read it by itself
source /etc/profile

# Includes
source $VESTA/func/main.sh
source $VESTA/conf/vesta.conf


#----------------------------------------------------------#
#                       Action                             #
#----------------------------------------------------------#

if [ -z "$BACKUP_SYSTEM" ]; then
    exit
fi

/usr/local/bin/ydcmd clean app:/monthly/ --type=file --keep=70d

for user in $(ls $VESTA/data/users); do
    check_suspend=$(grep "SUSPENDED='no'" $VESTA/data/users/$user/user.conf)
    log=$VESTA/log/backup.log
    if [ ! -z "$check_suspend" ]; then
        echo -e "================================" >> $log
        echo -e "$user" >> $log
        echo -e "--------------------------------\n" >> $log
        $BIN/v-backup-monthly-user $user >> $log 2>&1
        echo -e "\n--------------------------------\n\n" >> $log
    fi

    DATE=$(date +%F)
    backup=/backup/monthly/$user.$DATE.tar
    if [ -e "$backup" ]; then
        mv $backup $backup.zzz
        /usr/local/bin/ydcmd put $backup.zzz app:/monthly/ --retries=1
        rm $backup.zzz
    fi;
done

#----------------------------------------------------------#
#                       Vesta                              #
#----------------------------------------------------------#

# No Logging
#log_event "$OK" "$EVENT"

exit
